# Generated by Django 5.1.2 on 2024-10-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
