# Generated by Django 5.1.2 on 2024-10-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_debt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
