# Generated by Django 5.1.2 on 2024-10-10 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_debtrepayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_weeks', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('goal_type', models.CharField(choices=[('basic', 'Basic (e.g., House)'), ('luxury', 'Luxury (e.g., Car)')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
