# Generated by Django 5.1.2 on 2024-10-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_financialgoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtrepayment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
